"""init

Revision ID: 07fb14149bd4
Revises: None
Create Date: 2025-08-25 13:35:16.997131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fb14149bd4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('detected_lang', sa.String(length=8), nullable=True),
    sa.Column('target_lang', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_records')
    # ### end Alembic commands ###
