"""users and link to translations

Revision ID: 26244b8b8e2f
Revises: '826e1b669131'
Create Date: 2025-08-27 13:33:26.481852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26244b8b8e2f'
down_revision = '826e1b669131'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
