"""users and link to translations

Revision ID: 826e1b669131
Revises: '07fb14149bd4'
Create Date: 2025-08-27 13:25:27.752531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826e1b669131'
down_revision = '07fb14149bd4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('translation_records', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_translation_records_user_id'), 'translation_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'translation_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translation_records', type_='foreignkey')
    op.drop_index(op.f('ix_translation_records_user_id'), table_name='translation_records')
    op.drop_column('translation_records', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
