"""users and link to translations

Revision ID: af14d3ba2af6
Revises: '26244b8b8e2f'
Create Date: 2025-08-27 13:39:39.487233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af14d3ba2af6'
down_revision = '26244b8b8e2f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
