# Porta da API
server.port=8080

# Banco Postgres
spring.datasource.url=jdbc:postgresql://db:5432/translator
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=org.postgresql.Driver

# Erros
server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always
server.forward-headers-strategy=native

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ============================
# JWT
# ============================
# OBS: Defina um segredo forte aqui para assinar seus tokens
jwt.secret=IntrMvLCt0wNl8AhgqtP017Y5vkvh4WgfLfsULHhN2MFAhjWcbKD5BXikOF7mf85UI
jwt.access-token-minutes=60
jwt.expiration=3600000

libre.base-url=${LIBRE_BASE_URL:http://localhost:5000}

# ============================
# GOOGLE OAUTH2
# ============================
spring.security.oauth2.client.registration.google.client-id=145424326271-74vrp180vpl4n635rl0hpo9bjqnkh949.apps.googleusercontent.com/
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
# Este é o padrão do Spring Boot. Certifique-se de adicionar exatamente esta URL no console do Google
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google

# minutos para expirar token
app.reset.expMinutes=30

# caminho da página de reset no FRONT (usado no link do e-mail)
app.frontend.reset-path=/reset-password

logging.level.org.springframework.security=DEBUG